### PR TITLE
refactor: migrated deprecated Input and ValidationForm group components

### PR DESCRIPTION
**Pull request by abdullahwaheed**
### Ticket
[Migrate off deprecated Paragon components](https://github.com/openedx/frontend-wg/issues/102#)

### What has changed
Updated deprecated `ValidationFormGroup` to `Form.Group` and `Input` to `Form.Control`.

### CODE REVIEW

**Comment by mphilbrick211** [comment]
Hi @abdullahwaheed! I'm just following up on this PR - do you intend to keep this open and run the required tests?

**Comment by abdullahwaheed** [comment]
Hi @mphilbrick211. Yes this PR is for paragon form deprecations and is intended to keep. Please run tests on it

**Comment by mphilbrick211** [comment]
@colinbrash could you please allow tests to run?

**Comment by pshiu** [comment]
Closing to see if tests will re-run if re-opened.

**Comment by pshiu** [comment]
@abdullahwaheed Could take a look at the snapshot tests failure? (See CI failure.) I think snapshots might just need to be updated but am not sure.

**Comment by abdullahwaheed** [comment]
@pshiu let me check

**Comment by abdullahwaheed** [comment]
@pshiu audit step is failing again 😞

**Comment by arbrandes** [comment]
@abdullahwaheed, maybe a rebase will help?

**Comment by mphilbrick211** [comment]
Hi @abdullahwaheed! Friendly ping on Adolfo's suggestion to rebase.

**Comment by arbrandes** [comment]
Looks like tests have passed, but now we need a merge with master.  Care to do that, @abdullahwaheed?

Otherwise, any objections, @pshiu?

**Review by pshiu — APPROVED** [review]
LGTM, thanks @abdullahwaheed & @arbrandes!

**Comment by abdullahwaheed** [comment]
@arbrandes we can't merge in this repo. @pshiu could you please merge it?

**Pull request merged**
