### PR TITLE
fix: fixed vulnerabilities and updated allowlist in audit-ci.json

### PR DESCRIPTION
**Pull request by zubair-ce07**
Ticket
[REV-2654](https://2u-internal.atlassian.net/browse/REV-2654)

What has changed
Updated allowlisted advisories and fixed vulneerabilities.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @zubair-ce07!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

**Comment by natabene** [comment]
@zubair-ce07 Apologies for the problem with the CLA check, I will sort this out myself with Help Desk.

**Comment by natabene** [comment]
This has been tagged by the bot due to CLA issues. Once you hear from me about the CLA update, feel free to merge this.

**Comment by natabene** [comment]
@zubair-ce07 Can you do me a favor and remove the open-source-contribution label for now? I don't have permission to do it.

**Comment by zubair-ce07** [comment]
@natabene Yes sure.

**Comment by mphilbrick211** [comment]
Hi @zubair-ce07! I am just checking in to see if you plan to pursue this PR? If so, you will need to fill out the [Open edX CLA form](https://openedx.atlassian.net/wiki/spaces/COMM/pages/941457737/How+to+start+contributing+to+the+Open+edX+code+base). Please let me know if you have any questions.

**Comment by pshiu** [comment]
Thanks, @mphilbrick211! This ticket is actually out of date, so I will go ahead and close it.

**Pull request closed without merging**
