### PR TITLE
Paragon StatusAlert deprecation

### PR DESCRIPTION
**Pull request by abdullahwaheed**
### Ticket
[Migrate off deprecated Paragon components](https://github.com/openedx/frontend-wg/issues/102)

### What has changed
Removed deprecated `StatusAlert` component of paragon and updated it with `Alert`

### References
[Paragon StatusAlert](https://paragon-openedx.netlify.app/components/statusalert/)
[Paragon Alert](https://paragon-openedx.netlify.app/components/alert/)

### CODE REVIEW

**Comment by mphilbrick211** [comment]
Hi @abdullahwaheed - This branch is out-of-date, could you please rebase?

**Comment by abdullahwaheed** [comment]
@mphilbrick211 rebased the PR, its ready for review

**Comment by mphilbrick211** [comment]
Hi @abdullahwaheed! Looks like you have some tests that need to finish.
@arbrandes could you take a look at this and see if there's something that needs to be done to push this forward?

**Comment by arbrandes** [comment]
@abdullahwaheed, looks like this one is also failing a security audit.  Can you rebase on master to see if it goes away?

Also, @pshiu, sorry to pile these on you, but can you take a look as well?

**Comment by abdullahwaheed** [comment]
I have rebased it with master and now its ready to review and merge

**Comment by abdullahwaheed** [comment]
remove label: waiting on author

**Review by pshiu — APPROVED** [review]

**Comment by pshiu** [comment]
Will await close of https://github.com/openedx/frontend-app-payment/pull/688 to merge!

**Pull request merged**
