### PR TITLE
feat!: remove Transifex calls for OEP-58 | FC-0012

### PR DESCRIPTION
**Pull request by hopewise**
## Breaking change!

This change breaks the Jenkins transifex integration which has been deprecated in favor of the new GitHub Transifex App integration as part of [OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).

## Changes

 - Removes all direct use of `tx pull` and `tx push` commands from the micro-frontend in favor
of the [`atlas pull`](https://github.com/openedx/openedx-atlas/) command.
 - Remove source and language translations from the repositories, hence no `.json` files will be committed into the repos. 
 - `src/i18n/index.js` should export and empty array so the `make pull_translations` override it with the dynamic list of languages.
 - Remove the experimental `OPENEDX_ATLAS_PULL` flag to make `atlas pull` the default. 
 - Remove all Transifex related `Makefile` targets and other files.

Test results
------------

 - [ ] Verify that `make pull_translations` works as expected.

<details><summary>make pull_translations test results</summary>

```
# I've run the following commands:
$ make requirements
$ make pull_translations
$ git diff

# Output of the commmands:

make pull_translations
rm -rf src/i18n/messages
mkdir src/i18n/messages
cd src/i18n/messages \
      && atlas pull \
               translations/frontend-component-header/src/i18n/messages:frontend-component-header  \
               translations/frontend-component-footer/src/i18n/messages:frontend-component-footer \
               translations/paragon/src/i18n/messages:paragon \
               translations/frontend-app-payment/src/i18n/messages:frontend-app-payment
Pulling translation files
 - directory: translations/frontend-component-header/src/i18n/messages:frontend-component-header translations/frontend-component-footer/src/i18n/messages:frontend-component-footer translations/paragon/src/i18n/messages:paragon translations/frontend-app-payment/src/i18n/messages:frontend-app-payment
 - repository: openedx/openedx-translations
 - branch: main
 - filter: Not Specified
 - expand-glob: Not Specified
Creating a temporary Git repository to pull translations into "./translations_TEMP"...
^[Done.
Setting git sparse-checkout rules...
Done.
Pulling translation files from the repository...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 40 (delta 29), reused 25 (delta 18), pack-reused 0
Receiving objects: 100% (40/40), 32.41 KiB | 535.00 KiB/s, done.
Resolving deltas: 100% (29/29), done.
Your branch is up to date with 'origin/main'.
Done.
Copying translations from "./translations_TEMP/translations/frontend-component-header/src/i18n/messages" to "./frontend-component-header"...
Done.
Copying translations from "./translations_TEMP/translations/frontend-component-footer/src/i18n/messages" to "./frontend-component-footer"...
Done.
Copying translations from "./translations_TEMP/translations/paragon/src/i18n/messages" to "./paragon"...
Done.
Copying translations from "./translations_TEMP/translations/frontend-app-payment/src/i18n/messages" to "./frontend-app-payment"...
Done.
Removing temporary directory...
Done.

Translations pulled successfully!
./node_modules/.bin/intl-imports.js frontend-component-header frontend-component-footer paragon frontend-app-payment

```

</details> 

Merge timeline
-----------------------

This should only be merged after [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification) is fully implemented.

The timing announcement will be shared by @brian-smith-tcril on [#translations-project-fc-0012](https://openedx.slack.com/archives/C04R6TUJB7T) Open edX Slack channel.

Keep this pull request as a draft to prevent accidental merge.

### Pre-merge checklist

 - [ ] Wait for approval on https://github.com/openedx/wg-translations/issues/20

References
----------

This contribution is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).

Up-to-date project overview and details are available in the [Approach Memo and Technical Discovery: Translations Infrastructure Implementation](https://docs.google.com/document/d/11dFBCnbdHiCEdZp3pZeHdeH8m7Glla-XbIin7cnIOzU/edit#) document.

Join the conversation on [Open edX Slack #translations-project-fc-0012](https://openedx.slack.com/archives/C04R6TUJB7T).

Check the links above for full information about the overall project.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @hopewise!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Review by OmarIthawi — APPROVED** [review]
@itsjeyd @timmc-edx @brian-smith-tcril this one is ready for merge and 2U is ready for merging.

**Comment by OmarIthawi** [comment]
@brian-smith-tcril @spencertiberi the CI failure is a post-test issue.

Please check the link below and let me know how it can be fixed:

https://github.com/openedx/frontend-app-payment/actions/runs/8316512467/job/22756054443?pr=820#step:11:1

**Comment by brian-smith-tcril** [comment]
@OmarIthawi https://github.com/openedx/frontend-app-payment/pull/859 should fix it

**Review by brian-smith-tcril — APPROVED** [review]

**Comment by brian-smith-tcril** [comment]
@openedx/revenue-squad @spencertiberi this cannot be merged until a code owner approves it.

**Comment by itsjeyd** [comment]
For future reference, changes from #859 (now closed) were [added to this PR](https://github.com/openedx/frontend-app-payment/pull/859#issuecomment-2009394273).

So all that's left to get this PR over the finish line is code owner approval ⬆️.

Marking as `Ready for merge`.

**Comment by OmarIthawi** [comment]
@itsjeyd rebased with thanks!

**Review by julianajlk — APPROVED** [review]
FYI edx-internal changes to use atlas for the payment MFE has been done in https://github.com/edx/edx-internal/pull/10408

**Review by julianajlk — COMMENTED** [review]
Is there a reason `package-lock.json` is being modified with this work?

**Comment by brian-smith-tcril** [comment]
@OmarIthawi `package-lock.json` has been changed here without `package.json` being changed, do you know what happened there?

**Comment by OmarIthawi** [comment]
@brian-smith-tcril @julianajlk the package-lock.json changes were cherry picked from https://github.com/openedx/frontend-app-payment/pull/859. I don't fully understand the reason but it indeed fixed the build fail.

I've removed the commit and the build failed again, now I've cherry-picked the commit from https://github.com/openedx/frontend-app-payment/pull/859 and it's working again.

Please let me know if you're comfortable with merging the pull request as-is or I should wait for a fully review on https://github.com/openedx/frontend-app-payment/pull/859 and then rebase?

**Comment by julianajlk** [comment]
> @brian-smith-tcril @julianajlk the package-lock.json changes were cherry picked from #859. I don't fully understand the reason but it indeed fixed the build fail.
> 
> I've removed the commit and the build failed again, now I've cherry-picked the commit from #859 and it's working again.
> 
> Please let me know if you're comfortable with merging the pull request as-is or I should wait for a fully review on #859 and then rebase?

FYI @brian-smith-tcril has fixed the issue on https://github.com/openedx/frontend-app-payment/pull/862 and you should be able to rebase and get this PR green

**Comment by OmarIthawi** [comment]
Thanks @julianajlk @brian-smith-tcril this one should be rebased and ready for merge.

**Comment by openedx-webhooks** [comment]
@hopewise 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-payment&entry.867055334=https://github.com/openedx/frontend-app-payment/pull/820&entry.1484655318=https://github.com/hopewise&entry.752974735=2023-10-21+04:16&entry.1917517419=2024-03-27+12:30&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
