### PR TITLE
Supported Transifex languages in Makefile

### PR DESCRIPTION
**Pull request by abdullahwaheed**
### Ticket
[Expand list of supported Transifex languages to push/pull in Makefile](https://github.com/openedx/frontend-wg/issues/119)

### What has changed
Updated list of Transifex languages in make file to be consistent with Translation Working Groups's active languages. Removed unused files and added new files.
Updated the index file of languages accordingly

### CODE REVIEW

**Review by zubair-ce07 — APPROVED** [review]

**Comment by mphilbrick211** [comment]
Hi @abdullahwaheed! This branch is out-of-date and needs to be rebased.

**Comment by mphilbrick211** [comment]
Hi @abdullahwaheed! I'm just checking on this to see if you will still be running the tests on this?

**Comment by abdullahwaheed** [comment]
Hi @mphilbrick211 I can't run tests on this, i think people with write access of this repo can run tests here

**Comment by arbrandes** [comment]
@abdullahwaheed, mind rebasing?  Maybe the test failure will go away.

**Comment by sarina** [comment]
This branch is passing tests and has an approval. Can someone with write access @zubair-ce07 please merge?

**Comment by abdullahwaheed** [comment]
@zubair-ce07 / @mphilbrick211 could you please merge this? we don't have permission to merge this

**Comment by mphilbrick211** [comment]
Flagging for you @zubair-ce07 and @colinbrash.

@abdullahwaheed you will need to rebase to fix the branch date item. Thanks!

**Comment by abdullahwaheed** [comment]
@mphilbrick211 rebase done. Ready to review and merge

**Comment by sarina** [comment]
@zubair-ce07 you have already approved this. Could you please merge ASAP so the author doesn't need to continually rebase?

**Pull request merged**
