### PR TITLE
chore(i18n): add more languages

### PR DESCRIPTION
**Pull request by Yoiber071**
Add Transifex Working Group languages.

New language codes: it_IT,pt_PT,de_DE

@feanil 
@natabene

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Yoiber071!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by e0d** [comment]
@mphilbrick211 tests run.

**Comment by e0d** [comment]
@Yoiber071 looks like there are some test failures.

**Comment by Yoiber071** [comment]
Hi, Sorry for the late response, I've fixed the lint failures, and is ready to be tested again.

**Comment by mphilbrick211** [comment]
@colinbrash @openedx/revenue-squad would you mind reviewing this, and merging if it's good-to-go? Thanks!

**Comment by mphilbrick211** [comment]
> @colinbrash @openedx/revenue-squad would you mind reviewing this, and merging if it's good-to-go? Thanks!

Hi @colinbrash @openedx/revenue-squad - friendly ping on this.

**Review by zubair-ce07 — APPROVED** [review]
Changes LGTM 👍

**Comment by zubair-ce07** [comment]
Hi @Yoiber071. Can you please rebase the PR so I can merge it. Thanks

**Comment by openedx-webhooks** [comment]
@Yoiber071 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-payment&entry.867055334=https://github.com/openedx/frontend-app-payment/pull/709&entry.1484655318=https://github.com/Yoiber071&entry.752974735=2023-02-14+14:40&entry.1917517419=2023-03-28+10:49&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
